# Generated by Django 3.1.7 on 2021-03-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_couple_session_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Couple',
            new_name='Mapping',
        ),
    ]
